name: Rust

on:
  push:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        msrv: ["1.87.0"]

    steps:
    - uses: actions/checkout@v4
    - name: Install ${{ matrix.msrv }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.msrv }}
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
